# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  release-build:
    executor:
      name: android/android-machine
      resource-class: medium
      tag: default
    steps:
      - checkout
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/' >> ~/.circlerc
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run: source version.sh && incrementVersionCode
      - run: source version.sh && incrementVersionName
      - run: |
         cp $BASH_ENV bash.env
      - persist_to_workspace:
           root: .
           paths:
             - bash.env
      - run:
          name: Assemble release build
          command: |
            ./gradlew fsensor:assembleRelease
      - store_artifacts:
          path: fsensor/build/outputs/aar
      - persist_to_workspace:
          root: fsensor/build/outputs/aar
          paths:
            - fsensor-release.aar
      - run:
          name: "Commit version to GitHub"
          command: |
            git config user.email "build@tracqi.com"
            git config user.name "CircleCi"
            git add fsensor/version.properties
            git commit -m "[skip ci] Increment version code and name"
            git push --set-upstream origin v3.0

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run: |
          cat bash.env >> $BASH_ENV
      - attach_workspace:
          at: fsensor/build/outputs/aar
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION_NAME} ./fsensor/build/outputs/aar/fsensor-release.aar

workflows:
  release-build-workflow:
    jobs:
      - release-build
      - publish-github-release:
          requires:
            - release-build