package com.tracqi.fsensorapp.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF8D4E2A)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFFFDBCA)
val OnPrimaryContainer = Color(0xFF351000)
val Secondary = Color(0xFF765848)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFFFDBCA)
val OnSecondaryContainer = Color(0xFF2B160A)
val Tertiary = Color(0xFF636032)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFEAE5AA)
val OnTertiaryContainer = Color(0xFF1E1D00)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFFF8F5)
val OnBackground = Color(0xFF221A15)
val Surface = Color(0xFFFFF8F5)
val OnSurface = Color(0xFF221A15)
val SurfaceVariant = Color(0xFFF4DED4)
val OnSurfaceVariant = Color(0xFF52443C)
val Outline = Color(0xFF85746B)
val SurfaceContainerLow = Color(0xFFFEF1EB)
val SurfaceContainer = Color(0xFFF8EBE5)
val SurfaceContainerHigh = Color(0xFFF3E5DF)

val ChartRed = Color(0xFFE53935)
val ChartGreen = Color(0xFF43A047)
val ChartBlue = Color(0xFF1E88E5)
